proc format;

value TE_1F
  1="Yes"
  2="No"
;

value TE_2F
  1="Yes"
  2="No"
  3="Don't know / Not sure"
;

value TE_3F
  1="Male"
  2="Female"
;

value TE_4F
  1="Yes"
  2="Yes, but told only during pregnancy"
  3="No"
  4="No, pre-diabetes or borderline diabetes"
;

value TE_5F
  1="Employed for wages"
  2="Self-employed"
  3="Out of work for more than 1 year"
  4="Out of work for less than 1 year"
  5="A Homemaker"
  6="A Student"
  7="Retired"
  8="Unable to work"
;

value TE_6F
  1="BaseData"
  2="PartialData"
  3="AllData"
;

value TE_7F
  1="Excellent"
  2="Very good"
  3="Good"
  4="Fair"
  5="Poor"
;

value TE_8F
  1="Yes, only one"
  2="More than one"
  3="No"
  4="Don't know / Not sure"
;

value TE_9F
  1="Within past year"
  2="Within past 2 years"
  3="Within past 5 years"
  4="5 or more years ago"
  5="Never"
  6="Don't know / Not sure"
;

value TE_10F
  1="Yes"
  2="Yes, but told only during pregnancy"
  3="No"
  4="No, but pre-diabetes or borderline diabetes"
  5="Don't know / Not sure"
;

value TE_11F
  1="Yes"
  2="Yes, but told only during pregnancy"
  3="No"
  4="No, but told borderline high or pre-hypertensive"
  5="Don't know / Not sure"
;

value TE_12F
  1="Within the past year (anytime less than 12 months ago)"
  2="Within the past 2 years (1 year but less than 2 years ago)"
  3="Within the past 5 years (2 years but less than 5 years ago)"
  4="5 or more years ago"
  5="Don't know / Not sure"
;

value TE_13F
  1="Every day"
  2="Some Days"
  3="Not at all"
;

value TE_14F
  1="Within the past month (less than 1 month ago)"
  2="Within the past 3 months (1 month but less than 3 months ago)"
  3="Within the past 6 months (3 months but less than 6 months ago)"
  4="Within the past year (6 months but less than 1 year ago)"
  5="Within the past 5 years (1 year but less than 5 years ago)"
  6="Within the past 10 years (5 years but less than 10 years ago)"
  7="10 years or more"
  8="Never smoked regularly"
  9="Don't know / Not sure"
;

value TE_15F
  1="White"
  2="Black or African American "
  3="Asian"
  4="Native Hawaiian or Other Pacific Islander"
  5="American Indian or Alaska Native"
  6="Other"
;

value TE_16F
  1="January"
  2="February"
  3="March"
  4="April"
  5="May"
  6="June"
  7="July"
  8="August"
  9="September"
  10="October"
  11="November"
  12="December"
;

value TE_17F
  2009=" "
  2010=" "
;

value TE_18F
  1="A lot"
  2="A little"
  3="Not at all"
;

value TE_19F
  1="Mostly sitting or standing"
  2="Mostly walking"
  3="Mostly heavy labor or physically demanding work"
;

value TE_20F
  1="Always"
  2="Usually"
  3="Sometimes"
  4="Rarely"
  5="Never"
;

value TE_21F
  1="Very satisfied"
  2="Satisfied"
  3="Dissatisfied"
  4="Very dissatisfied"
;

value TE_22F
  1="Only one"
  2="Two"
  3="Three or more"
  4="Don't know / Not sure"
;

value TE_23F
  1="Yes"
  2="Yes, during pregnancy"
  3="No"
  4="Don't know / Not sure"
;

value TE_24F
  1="Yes"
  2="Yes, but told only during pregnancy"
  3="No"
  4="No, pre-diabetes or borderline diabetes"
;

value TE_25F
  1="Per day"
  2="Per week"
  3="Per month"
  4="Per year"
;

value TE_26F
  1="Within the past month (anytime less than 1 month ago)"
  2="Within the past year (1 month but less than 12 months ago) "
  3="Within the past 2 years (1 year but less than 2 years ago) "
  4="2 or more years ago"
  5="Never"
  6="Don't know / Not sure"
;

value TE_27F
  1="Yes"
  2="No"
  3="Do not use salt"
  4="Don't know / Not sure"
;

value TE_28F
  1="Yes"
  2="No"
  3="Do not drink"
  4="Don't know / Not sure"
;

value TE_29F
  1="Yes"
  2="Yes, but told only during pregnancy"
  3="No"
  4="Told borderline or pre-hypertensive"
  5="Don't know / Not sure"
;

value TE_30F
  1="Take them to the hospital"
  2="Tell them to call their doctor "
  3="Call 911"
  4="Call their spouse or a family member"
  5="Do something else"
  6="Don't know / Not sure"
;

value TE_31F
  0="Not at any time"
  1="Less than once a week"
  2="Once or twice a week"
  3="More than 2 times a week, but not every day"
  4="Every day, but not all the time"
  5="Every day, all the time"
;

value TE_32F
  0="None"
  1="One or two"
  2="Three to four"
  3="Five"
  4="Six to ten "
  5="More than ten"
;

value TE_33F
  0="Never"
  1="1 to 14 days"
  2="15 to 24 days"
  3="25 to 30 days"
;

value TE_34F
  0="Never (include no attack in past 30 days)"
  1="1 to 4 times (in the past 30 days)"
  2="5 to 14 times (in the past 30 days)"
  3="15 to 29 times (in the past 30 days)"
  4="30 to 59 times (in the past 30 days)"
  5="60 to 99 times (in the past 30 days)"
  6="100 or more times (in the past 30 days)"
;

value TE_35F
  1="I can do everything I would like to do"
  2="I can do most things I would like to do"
  3="I can do some things I would like to do"
  4="I can hardly do anything I would like to do"
;

value TE_36F
  1="White"
  2="Black or African America"
  3="Hispanic or Latino "
  4="Asian"
  5="Native Hawaiian or Other Pacific Islander "
  6="American Indian or Alaska Native"
  7="Some other group "
  8="Don't know / Not sure"
;

value TE_37F
  1="Never"
  2="Once a year"
  3="Once a month"
  4="Once a week"
  5="Once a day"
  6="Once an hour"
  7="Constantly"
  8="Don't know / Not sure"
;

value TE_38F
  1="Worse than other races"
  2="The same as other races"
  3="Better than other races"
  4="Worse than some races, better than others"
  5="Only encountered people of the same race "
  6="Don't know / Not sure"
;

value TE_39F
  1="Worse than other races"
  2="The same as other races"
  3="Better than other races"
  4="Worse than some races, better than others"
  5="Only encountered people of the same race "
  6="No health care in past 12 months "
  7="Don't know / Not sure"
;

value TE_40F
  1="All of the time"
  2="Most of the time"
  3="Some of the time"
  4="A little of the time"
  5="None of the time"
  6="Don't know / Not sure"
;

value TE_41F
  1="Agree strongly"
  2="Agree slightly"
  3="Neither agree nor disagree"
  4="Disagree slightly"
  5="Disagree strongly"
;

value TE_42F
  1="Own"
  2="Rent"
  3="Other Arrangement"
  4="Don't know / Not sure"
;

value TE_43F
  1="Always"
  2="Usually"
  3="Sometimes"
  4="Rarely"
  5="Never"
;

value TE_44F
  1="Paid by salary"
  2="Paid by the hour"
  3="Paid by the job/task (e.g. commission, piecework)"
  4="Paid some other way"
  7="Don't know / Not sure"
;

value TE_45F
  0="Once a month or less"
  1="2-3 times a month"
  2="1-2 times a week"
  3="3-4 times a week"
  4="5 or more times a week"
;

value TE_46F
  0="Less than 1/week"
  1="Once a week"
  2="2-3 times a week"
  3="4-6 times a week"
  4="Once a day"
  5="2 or more times a day"
;

value TE_47F
  0="I have never tried marijuana"
  1="Less then 9 years old"
  2="9-12 years old"
  3="13-16 years old"
  4="17-20 years old"
  5="21-24 years"
  6="25 or older"
;

value TE_48F
  0="0 times"
  1="1-2 times"
  2="3-9 times"
  3="10-19 times"
  4="20-39 times"
  5="40-99 times"
  6="100 or more times"
;

value TE_49F
  0="0 times"
  1="1-2 times"
  2="3-9 times"
  3="10-19 times"
  4="20-39 times"
  5="40 or more times"
;

value TE_50F
  0="I have never tried cocaine"
  1="Less then 9 years old"
  2="9-12 years old"
  3="13-16 years old"
  4="17-20 years old"
  5="21-24 years"
  6="25 or older"
;

value TE_51F
  0="Not at all"
  1="A little bit"
  2="Moderately"
  3="Quite a bit"
  4="Extremely"
;

value TE_52F
  1="Excellent"
  2="Good"
  3="Fair"
  4="Poor"
;

value TE_53F
  1="Never"
  2="Sometimes"
  3="Always"
;

value TE_54F
  1="From my mother"
  2="From my father"
  3="From my grandmother or other relatives"
  4="From my friends"
  5="From the doctor"
  6="From a book about baby/child care"
  7="From TV"
;

value TE_55F
  1="Yes"
  2="No"
;

value TE_56F
  1="Doctor's office (solo or group practice)"
  2="Public Health Clinic"
  3="Hospital outpatient clinic"
  4="Urgent care center"
  5="Emergency room"
  6="Other"
;

value TE_57F
  1="Very satisfied"
  2="Satisfied"
  3="Dissatisfied"
  4="Very dissatisfied"
;

value TE_58F
  1="Medicaid"
  2="Medicare"
  3="Medical insurance received through an employer"
  4="Medical insurance purchased as an individual"
  5="Other"
  6="Not covered by any medical insurance"
;

run;
