proc format;

VALUE YR_CHK
	1 = 'YES'
	. = 'NO '
;


value TE_1F
  1='NO'
  2='YES'
;


value TE_2F
  1='per hour'
  2='per day'
  3='per week'
  4='every 2 weeks'
  5='twice a month'
  6='each month'
  7='per Year'
  8='other'
;


value TE_3F
  1='per hour'
  2='per day'
  3='per week'
  4='every 2 weeks'
  5='twice a month'
  6='each month'
  7='per year'
;


value TE_4F
  1='Biological mother'
  2='Biological father'
  3='Adoptive mother'
  4='Adoptive father'
  5='Foster mother'
  6='Foster father'
  7='Stepmother'
  8='Stepfather'
  9='Aunt'
  10='Uncle'
  11='Maternal grandmother'
  12='Maternal grandfather'
  13='Paternal grandmother'
  14='Paternal grandfather'
  15='Sister'
  16='Brother'
  17='Stepsister'
  18='Stepbrother'
  19='Half sister'
  20='Half brother'
  21='Adoptive sister'
  22='Adoptive brother'
  23='Daughter'
  24='Son'
  25='Foster daughter'
  26='Foster son'
  27='Stepdaughter (child of spouse or partner)'
  28='Stepson (child of spouse or partner)'
  29='Partner (unmarried, living together)'
  30='Spouse (married)'
  31='Girlfriend (not a member of the household)'
  32='Boyfriend (not a member of the household)'
  33='Mother-in-law (mother of spouse or partner)'
  34='Father-in-law (father of spouse or partner)'
  35='Niece'
  36='Nephew'
  37='Friend'
  38='Other relative'
  39='Other non-relative'
;


value TE_5F
  1='Less than 9th grade'
  2='9th to 12th grade'
  3='GED enrolled'
  4='GED obtained/ no college'
  5='High School graduate/ no college'
  6='Some community college/technical school'
  7='Completed community college/technical school/associates degree'
  8='Some four-year college'
  9='Completed four-year college degree (B.A., B.S.)'
  10='Some graduate school'
  11='Completed master s training (M.A., M.S., M.Ed., Ed.S., MBA)'
  12='Completed Ph.D, Ed.D, M.D., J.D.'
;


value TE_6F
  1='In a GED program to get a HS diploma'
  2='At a vocational/technical school'
  3='Community College'
  4='Four-year undergraduate college or university'
  5='In graduate school'
  6='Other'
;


value TE_7F
  1='No'
  2='Yes - High School'
  3='Yes - GED'
;


value TE_8F
  1='A. Obtain a GED'
  2='B. Complete vocational/technical trainging'
  3='C. Obtain a certificate at community college'
  4='D. Some college'
  5='E. College/university graduation'
  6='F. Get a graduate or professional degree'
  7='G. Other'
;


value TE_9F
  1='Much better than others in my class'
  2='A little better than the others'
  3='About the same'
  4='A little worse than the others'
  5='Much worse than the others (could not keep up)'
;


value TE_10F
  1='Female'
  2='Male'
;


value TE_11F
  1='In own home'
  2='In parent s home'
  3='In someone else s home'
  4='College housing'
  5='Military base'
  6='Group home, half-way house, or social rehabilitation facility'
  7='Physical rehabilitation facility or nursing home'
  8='Prison'
  9='Homeless'
  10='Other'
;


value TE_12F
  1='Rent'
  2='Own'
;


value TE_13F
  1='Relative'
  2='Friend'
  3='Spouse or Partner'
  4='Employer'
  5='Landlord/Landlady'
  6='Other'
;


value TE_14F
  1='House'
  2='Apartment'
  3='Mobile home or trailer'
  4='Duplex/townhouse'
  5='Condo'
  6='Dorm Room'
  7='Prison Cell'
  8='Other'
  9='Not applicable because homeless'
;


value TE_15F
  1='In own home'
  2='In parent s home'
  3='In someone else s home'
  4='College Housing'
  5='Military Base'
  6='Group home, half-way house, or social rehabilitation facility'
  7='Physical rehabilitation facility or nursing home'
  8='Prison'
  9='Homeless'
  10='Other'
;


value TE_16F
  1='Rent'
  2='Own'
;


value TE_17F
  1='Month'
  2='Year'
  3='Week'
;


value TE_18F
  1='Relative'
  2='Friend'
  3='Spouse or Partner'
  4='Employer'
  5='Other'
;

value TE_19F
  1='Month'
  2='Year'
  3='Week'
;


value TE_20F
  1='House'
  2='Apartment'
  3='Mobile home or trailer'
  4='Duplex/townhouse'
  5='Condo'
  6='Dorm Room'
  7='Prison Cell'
  8='Other'
  9='Not applicable because homeless'
;


value TE_21F
  1='Alone'
  2='With Others'
;


value TE_22F
  1='Army'
  2='Coast Guard'
  3='Air Force'
  4='Marines'
  5='Navy'
;


value TE_23F
  1='Reserve'
  2='Active'
;


value TE_24F
  1='Very satisfied'
  2='Satisfied'
  3='Neither satisfied nor dissatisfied'
  4='Dissatisfied'
  5='Very dissatisfied'
;


value TE_25F
  1='Very satisfied'
  2='Satisfied'
  3='Neither satisfied nor dissatisfied'
  4='Dissatisfied'
  5='Very dissatisfied'
;


value TE_26F
  1='Left for a better Job'
  2='Left for family responsibilities'
  3='Left to attend school'
  4='Transportation problems (Could not get to job)'
  5='Quit because disliked work'
  6='Quit because disliked people worked with'
  7='Fired'
  8='Other - Please specify'
;


value TE_27F
  1='Left for a better Job'
  2='Left for family responsibilities'
  3='Left to attend school'
  4='Transportation problems (Could not get to job)'
  5='Quit because disliked work'
  6='Quit because disliked people worked with'
  7='Fired'
  8='Other - Please specify'
;


value TE_28F
  1='Keeping house and/or taking care of children'
  2='In school'
  3='Looking for work'
  4='Traveling'
  5='Other'
;


value TE_29F
  1='Before taxes (gross income)'
  2='After taxes (net income)'
  3='Untaxed (Subject does not pay taxes on this income)'
;


value TE_30F
  1='AFDC benefit'
;


value TE_31F
  1='Food stamps'
;


value TE_32F
  1='Housing'
;
value TE_33F
  1='WIC benefit'
;


value TE_34F
  1='Fuel benefit'
;


value TE_35F
  1='Unemployment benefit'
;


value TE_36F
  1='Other welfare benefit'
;


value TE_37F
  1='Before taxes (gross income)'
  2='After taxes (net income)'
  3='Did not pay taxes on this income'
;


value TE_38F
  1='Look for a job'
  2='Work for pay'
  3='Work in an unpaid position'
  4='Attend school or training'
  5='Other'
;


value TE_39F
  1='Before taxes (gross income)'
  2='After taxes (net income)'
  3='Untaxed (Spouse/Partner does not pay taxes on this income)'
;


value TE_40F
  1='Less than $10,000'
  2='$10,000 to $14,999'
  3='$15,000 to $19,999'
  4='$20,000 to $29,999'
  5='$30,000 to $39,999'
  6='$40,000 to $49,999'
  7='$50,000 to $74,999'
  8='$75,000 or more'
;


value TE_41F
  1='No'
  2='Yes, 1 residence'
  3='Yes, multiple residences'
;


value TE_42F
  1='Got a Job'
  2='Working in the same job, but got more hours or a raise'
  3='Got a better job'
  4='Got married or remarried'
  5='Moved in with a partner in a marriage-like relationship'
  6='Moved in with family'
  7='Moved to another county or state'
  8='Earning increased past limit'
  9='Assests were too high'
  10='Did not follow program rules'
  11='Reached the end of the time limit for benefits'
  12='Other'
;


value TE_43F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times a month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_44F
  1='Very close'
  2='Somewhat close'
  3='In the middle'
  4='Not very close'
  5='Not close at all'
;


value TE_45F
  1='An adoptive parent'
  2='Step-mother'
  3='Maternal grandmother'
  4='Paternal grandmother'
  5='A foster parent'
  6='Another relative'
  7='Other'
;


value TE_46F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times a month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_47F
  1='Very close'
  2='Somewhat close'
  3='In the middle'
  4='Not very close'
  5='Not close at all'
;


value TE_48F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times a month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;
value TE_49F
  1='Very close'
  2='Somewhat close'
  3='In the middle'
  4='Not very close'
  5='Not close at all'
;


value TE_50F
  1='An adoptive parent'
  2='Step-father'
  3='Maternal grandfather'
  4='Paternal grandfather'
  5='A foster parent'
  6='Another relative'
  7='Other'
;


value TE_51F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times a month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_52F
  1='Very close'
  2='Somewhat close'
  3='In the middle'
  4='Not very close'
  5='Not close at all'
;


value TE_53F
  1='Still Married'
  2='Separated'
  3='Divorced'
  4='Widowed'
;


value TE_54F
  1='Married'
  2='Single, Never Married'
  3='Separated'
  4='Divorced'
  5='Widowed'
;


value TE_55F
  1='Less than 6 months'
  2='More than 6 months but less than 1 year'
  3='More than 1 year but less than 2 years'
  4='2 or more years'
;


value TE_56F
  1='Male'
  2='Female'
;


value TE_57F
  1='Biological child'
  2='Adopted child'
;


value TE_58F
  1='Male'
  2='Female'
;


value TE_59F
  1='Step-child'
  2='Foster child'
  3='Other-Relative'
  4='Other-Nonrelative'
;


value TE_60F
  1='Biological mother'
  2='Biological father'
  3='Adoptive mother'
  4='Adoptive father'
  5='Foster mother'
  6='Foster father'
  7='Step-mother'
  8='Step-father'
  9='Aunt'
  10='Uncle'
  11='Other'
;


value TE_61F
  1='Excellent'
  2='Very Good'
  3='Good'
  4='Fair'
  5='Poor'
  6='Don t Know'
;


value TE_62F
  1='Hearing problems or deafness'
  2='Delayed speech or other problems with speaking or understanding what is said'
  3='Visual problems even if wearing glasses'
  4='Slow to learn or developmentally delayed'
  5='Allergies or hay fever (do not include allergies to medicines)'
  6='Asthma'
  7='Any other chronic respiratory, lung, or breathing problem'
  8='A chronic heart problem'
  9='Sickle cell anemia'
  10='Epilepsy, convulsions, or seizures without fever'
  11='Chronic othopedic, bone, or joint problems'
  12='Cerebral palsy'
  13='Cystic fibrosis'
  14='Cancer'
  15='Hemophilia'
  16='HIV or AIDS'
  17='Any other health problems requiring medical specialists'
;


value TE_63F
  1='Never gets sick or needs care'
  2='Gets sick but doesn t go anywhere for healthcare'
  3='Hospital-based-clinic'
  4='Emergency room'
  5='Community health department or clinic'
  6='Private doctor s office'
  7='Infirmary at school'
  8='Military hospital or clinic'
  9='Employee health clinic atwork'
  10='Other'
;


value TE_64F
  1='No'
  2='Yes'
  3='Child spends equal time at 2 residences'
;


value TE_65F
  1='Biological Mother'
  2='Biological Father'
  3='Step-mother'
  4='Step-father'
  5='Adoptive mother'
  6='Adoptive father'
  7='Maternal grandarent(s)'
  8='Other maternal relative(s)'
  9='Paternal grandparent(s)'
  10='Other paternal relative(s)'
  11='Child s sibling(s) or step-sibling(s)'
  12='Foster mother'
  13='Foster father'
  14='Friends'
  15='Don t Know'
  16='Other'
;


value TE_66F
  1='Biological Mother'
  2='Biological Father'
  3='Step-mother'
  4='Step-father'
  5='Adoptive mother'
  6='Adoptive father'
  7='Maternal grandparent(s)'
  8='Other maternal relative(s)'
  9='Paternal grandparent(s)'
  10='Other paternal relative(s)'
  11='Child s sibling(s) or step-sibling(s)'
  12='Foster mother'
  13='Foster father'
  14='Friends'
  15='Don t Know'
  16='Other'
;


value TE_67F
  1='Someone other than interviewee'
  2='Interviewee, but not other biological parent'
  3='Joint custody situation where child lives with both parents, but in two different households'
  4='Interviewee, but child is a foster child'
  5='Both parents together in same home, including interviewee'
;


value TE_68F
  1='Within 1 mile'
  2='1 to 10 miles'
  3='11 to 50 miles'
  4='51 to 100 miles'
  5='101-200 miles'
  6='More than 200 miles'
  7='Don t Know'
;


value TE_69F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times per month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_70F
  1='Always'
  2='Most of the time'
  3='Sometimes'
  4='Rarely'
  5='Never'
;


value TE_71F
  1='Mother has sole custody'
  2='Father has sole custody'
  3='Joint custody'
  4='Other'
;


value TE_72F
  1='No'
  2='Yes'
  3='Sometimes'
;


value TE_73F
  1='None'
  2='1 or 2'
  3='3 to 5'
  4='6 to 8'
  5='9 to 11'
  6='All payments'
;


value TE_74F
  1='Bought clothes, toys, or presents for holidays or birthdays'
  2='Paid for medical or dental expenses'
  3='Given extra money to help out with costs (exclsuive of support payments'
  4='Helped pay for child care expenses'
  5='Other'
;


value TE_75F
  1='Biological mother'
  2='Biological father'
  3='Step-mother'
  4='Step-father'
  5='Adoptive mother'
  6='Adoptive father'
  7='Other'
;


value TE_76F
  1='Within 1 mile'
  2='1 to 10 miles'
  3='11 to 50 miles'
  4='51 to 100 miles'
  5='101-200 miles'
  6='More than 200 miles'
;


value TE_77F
  1='Daily'
  2='More than once a week'
  3='Once a week'
  4='1 or 2 times per month'
  5='5 or 6 times a year'
  6='3 or 4 times a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_78F
  1='Always'
  2='Most of the time'
  3='Sometimes'
  4='Rarely'
  5='Never'
;


value TE_79F
  1='Mother has sole custody'
  2='Father has sole custody'
  3='Joint custody'
  4='Other'
;


value TE_80F
  1='No'
  2='Yes'
  3='Sometimes'
;


value TE_81F
  1='None'
  2='1 or 2'
  3='3 to 5'
  4='6 to 8'
  5='9 to 11'
  6='All payments'
;


value TE_82F
  1='Bought clothes, toys, or presents for holidays or birthdays'
  2='Paid for medical or dental expenses'
  3='Given extra money to help out with costs (exclsuive of support payments'
  4='Helped pay for child care expenses'
  5='Other'
;


value TE_83F
  1='Within the past 3 months'
  2='4-6 months ago'
  3='Within the past year'
  4='Longer than 1 but less than 2 years'
  5='Longer than 2 years but less than 5 years ago'
  6='More than 5 years ago'
  7='Other'
;


value TE_84F
  1='Mother only'
  2='Father only'
  3='Both biological parents'
;


value TE_85F
  1='No'
  2='Yes'
  3='Sometimes'
;

value TE_86F
  1='Biological Mother'
  2='Biological Father'
  3='Step-mother'
  4='Step-father'
  5='Adoptive mother'
  6='Adoptive father'
  7='Maternal grandarent(s)'
  8='Other maternal relative(s)'
  9='Paternal grandparent(s)'
  10='Other paternal relative(s)'
  11='Other'
;


value TE_87F
  1='Biological Mother'
  2='Biological Father'
  3='Step-mother'
  4='Step-father'
  5='Adoptive mother'
  6='Adoptive father'
  7='Maternal grandarent(s)'
  8='Other maternal relative(s)'
  9='Paternal grandparent(s)'
  10='Other paternal relative(s)'
  11='Other'
;


value TE_88F
  1='Bought clothes, toys, or presents for holidays or birthdays'
  2='Paid for medical or dental expenses'
  3='Given extra money to help out with costs (exclsuive of support payments'
  4='Helped pay for child care expenses'
  5='Other'
;


value TE_89F
  1='Excellent'
  2='Very Good'
  3='Good'
  4='Fair'
  5='Poor'
;


value TE_90F
  1='Hearing problems or deafness'
  2='Visual problems even if wearing glasses'
  3='Allergies or hay fever (do not include allergies to medicines)'
  4='Asthma'
  5='Any other chronic respiratory, lung, or breathing problem '
  6='A chronic heart condition'
  7='Diabetes'
  8='High blood pressure'
  9='Stroke'
  10='Chronic gastrointestinal conditions (indigestion, mal-absorption, reflux)'
  11='Simple anemia '
  12='Sickle cell anemia '
  13='Any STDs '
  14='Problems of infertility '
  15='Any problems with pregnancies (for women) '
  16='Kidney disease '
  17='Epilepsy, convulsions, or seizures without fever '
  18='Chronic orthopedic, bone, or joint problems (arthritis; sports injuries)'
  19='Cerebral palsy '
  20='Cystic fibrosis '
  21='Cancer '
  22='HIV or AIDS '
  23='Problems with remembering things or mental confusion '
  24='Trouble sleeping or trouble staying awake '
  25='Mental health problems (Please specify) '
  26='Any other health problem requiring medical specialists? '
;


value TE_91F
  1='No health insurance'
  2='Covered by husband s or wife s insurance policy'
  3='Get own insurance through work'
  4='Get insurance through a union '
  5='Get insurance because of attending school '
  6='Covered because of being on active duty in the military'
  7='Buy private insurance on your own'
  8='Covered by Medicaid '
  9='You don t know what your health insurance situation is '
  10='Other'
;


value TE_92F
  1='Never get sick or need care'
  2='Get sick but don t go anywhere for health care'
  3='Hospital-based clinic '
  4='Emergency room'
  5='Community health department or clinic'
  6='Private doctor s office'
  7='Infirmary at school '
  8='Military hospital or clinic '
  9='Employee health clinic at my work '
  10='Other'
;
value TE_93F
  1='Within the past 3 months'
  2='4-6 months ago'
  3='Within the past year '
  4='Longer than one but less than 2 years ago'
  5='More than two years ago '
;


value TE_94F
  1='Within the past 3 months'
  2='4-6 months ago'
  3='Within the past year '
  4='Longer than one but less than 2 years ago'
  5='More than two years ago '
;


value TE_95F
  1='Within the past 3 months'
  2='4-6 months ago'
  3='Within the past year '
  4='Longer than one but less than 2 years ago'
  5='More than two years ago '
;


value TE_96F
  1='Very underweight'
  2='Slightly underweight'
  3='About the right weight'
  4='Slightly overweight'
  5='Very overweight'
;


value TE_97F
  1='Trying to lose weight'
  2='Trying to gain weight or bulk up'
  3='Trying to stay the same'
  4='Not trying to do anything about weight at this point'
;


value TE_98F
  1='Misdemeanor'
  2='Felony'
;


value TE_99F
  1='Paid a fine'
  2='Placed on probation'
  3='Required to do community service'
  4='Incarcaration'
;


value TE_100F
  1='State training camp'
  2='Youth Camp'
  3='County jail'
  4='State prison'
  5='Federal Prison'
;


value TE_101F
  1='Misdemeanor'
  2='Felony'
;


value TE_102F
  1='Paid a fine'
  2='Placed on probation'
  3='Required to do community service'
  4='Incarcaration'
;


value TE_103F
  1='County jail'
  2='First offender facility'
  3='State prison'
  4='Federal prison'
;


value TE_104F
  1='Very Important'
  2='Sort of important'
  3='Not very important'
  4='Not important at all'
;


value TE_105F
  1='Daily'
  2='More than once a week'
  3='Once a week '
  4='1 or 2 times per month'
  5='5 or 6 times in a year'
  6='3 or 4 times in a year'
  7='Once or twice a year'
  8='Less than once a year'
  9='Never'
;


value TE_106F
  1='Have officially joined some religious congregation'
  2='Teach classes for children or adults'
  3='Serve on committees or boards'
  4='Usher'
  5='Choir or other musical activities'
  6='Scriptural study or spiritual growth groups '
  7='Go on retreats'
  8='Other'
;


value TE_107F
  1='Child or youth organizations (e.g. Little League, Scouts)'
  2='Service organizations (e.g. Civitan, Masons, Big Brother, Big Sister, Volunteers for Youth)'
  3='Volunteer at a homeless shelter or other IFC activity '
  4='Habitat for Humanity volunteer '
  5='Ethnic solidarity or support groups (e.g. NAACP; Urban League)'
  6='Active in a political party (e.g. Democratic party, Republican Party)'
  7='Served on the boards of community centers (e.g. City parks or community centers,  Y )'
  8='Served on the Board of a child care or child education organization (e.g. Head Start, Chapel Hill Day Care Center, etc.)'
  9='Hospital or nursing home volunteers'
  10='Neighborhood improvement organizations, Neighborhood Watch '
  11='Environmental or Conservation groups (e.g. Triangle Nature Conservancy)'
  12='Animal shelter'
  13='Participated in a Red Cross Blood drive'
  14='Volunteered for disaster relief activities'
  15='Other'
;


value TE_108F
  1='Married'
  2='Single, Never Married'
  3='Separated'
  4='Divorced'
  5='Widowed'
;

run;